use std::collections::{HashMap, HashSet};
use crate::compiler::dag::{DagNode, ExecutionDag};
use crate::ast::Severity;

/// Multi-pass optimizer that transforms a raw node list into an efficient plan.
pub struct Optimizer {
    /// Drop blocking-severity violations immediately when one is found for a column,
    /// skipping expensive downstream checks on that column.
    pub stop_on_blocking: bool,
}

impl Default for Optimizer {
    fn default() -> Self {
        Self { stop_on_blocking: true }
    }
}

impl Optimizer {
    pub fn optimize(&self, nodes: Vec<DagNode>) -> ExecutionDag {
        let nodes = self.deduplicate(nodes);
        let nodes = self.fuse_null_checks(nodes);
        let nodes = self.sort_by_cost(nodes);
        ExecutionDag::new(nodes)
    }

    /// Remove identical nodes (same column + same check kind).
    fn deduplicate(&self, nodes: Vec<DagNode>) -> Vec<DagNode> {
        let mut seen: HashSet<String> = HashSet::new();
        nodes
            .into_iter()
            .filter(|n| {
                // Use JSON-serialised node as dedup key (simple and correct).
                let key = format!("{n:?}");
                seen.insert(key)
            })
            .collect()
    }

    /// If a column already has a NullCheck, suppress redundant null checks
    /// generated by QualityMetricCheck(completeness) for the same column.
    fn fuse_null_checks(&self, nodes: Vec<DagNode>) -> Vec<DagNode> {
        let null_checked: HashSet<String> = nodes
            .iter()
            .filter_map(|n| {
                if matches!(n, DagNode::NullCheck { .. }) {
                    Some(n.column().to_string())
                } else {
                    None
                }
            })
            .collect();

        nodes
            .into_iter()
            .filter(|n| {
                // Drop completeness quality checks for columns that already have
                // an explicit NullCheck — the NullCheck is cheaper and equivalent.
                if let DagNode::QualityMetricCheck {
                    column,
                    metric: crate::ast::MetricFn::Completeness,
                    ..
                } = n
                {
                    !null_checked.contains(column.as_str())
                } else {
                    true
                }
            })
            .collect()
    }

    /// Sort nodes so that:
    /// 1. Cheaper checks (type, null) run before expensive ones (regex, uniqueness).
    /// 2. Blocking-severity checks run before lower-severity ones on the same column
    ///    so we can bail early on hard failures.
    /// 3. Profile nodes always run last (they are free metadata, not gating).
    fn sort_by_cost(&self, mut nodes: Vec<DagNode>) -> Vec<DagNode> {
        nodes.sort_by(|a, b| {
            // Primary sort: column name (group column scans together)
            let col_cmp = a.column().cmp(b.column());
            if col_cmp != std::cmp::Ordering::Equal {
                return col_cmp;
            }
            // Secondary: blocking first within a column
            let sev_order = |n: &DagNode| match n.severity() {
                Severity::Blocking => 0u8,
                Severity::Error    => 1,
                Severity::Warning  => 2,
                Severity::Info     => 3,
            };
            let sev_cmp = sev_order(a).cmp(&sev_order(b));
            if sev_cmp != std::cmp::Ordering::Equal {
                return sev_cmp;
            }
            // Tertiary: cost estimate
            a.cost().cmp(&b.cost())
        });
        nodes
    }

    /// Build per-column node groups for parallel execution.
    pub fn group_by_column(dag: &ExecutionDag) -> HashMap<String, Vec<&DagNode>> {
        let mut map: HashMap<String, Vec<&DagNode>> = HashMap::new();
        for node in &dag.nodes {
            map.entry(node.column().to_string())
                .or_default()
                .push(node);
        }
        map
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Severity;
    use crate::compiler::dag::DagNode;

    #[test]
    fn test_dedup_removes_identical_nodes() {
        let n1 = DagNode::NullCheck { column: "id".into(), severity: Severity::Error };
        let n2 = DagNode::NullCheck { column: "id".into(), severity: Severity::Error };
        let opt = Optimizer::default();
        let result = opt.optimize(vec![n1, n2]);
        assert_eq!(result.nodes.len(), 1);
    }

    #[test]
    fn test_sort_puts_cheap_checks_first() {
        let nodes = vec![
            DagNode::OutlierDetection { column: "age".into(), method: "iqr".into(), severity: Severity::Error },
            DagNode::NullCheck { column: "age".into(), severity: Severity::Error },
            DagNode::RegexCheck { column: "age".into(), pattern: ".+".into(), severity: Severity::Error },
        ];
        let opt = Optimizer::default();
        let result = opt.optimize(nodes);
        // NullCheck (cost=1) should come before RegexCheck (cost=4) before OutlierDetection (cost=8)
        let costs: Vec<u8> = result.nodes.iter().map(|n| n.cost()).collect();
        assert!(costs.windows(2).all(|w| w[0] <= w[1]));
    }
}
